{"Title": "Talk to Me", "Boxoffice in Million": 47.6, "Runtime in Minutes": 95, "Original Language": "English", "Director": "DannyPhilippou", "release_month": "Jul", "rating": "R", "files": []}
{"Title": "Dungeons & Dragons: Honor Among Thieves", "Boxoffice in Million": 93.2, "Runtime in Minutes": 134, "Original Language": "English", "Director": "JonathanM.Goldstein", "release_month": "Mar", "rating": "PG-13", "files": []}
{"Title": "BlackBerry", "Boxoffice in Million": 1.5, "Runtime in Minutes": 119, "Original Language": "English", "Director": "MattJohnson", "release_month": "May", "rating": "R", "files": []}
{"Title": "M3GAN", "Boxoffice in Million": 95.0, "Runtime in Minutes": 102, "Original Language": "English", "Director": "GerardJohnstone", "release_month": "Jan", "rating": "PG-13", "files": []}
{"Title": "Teenage Mutant Ninja Turtles: Mutant Mayhem", "Boxoffice in Million": 118.4, "Runtime in Minutes": 99, "Original Language": "English", "Director": "JeffRowe", "release_month": "Aug", "rating": "PG", "files": []}
{"Title": "The Holdovers", "Boxoffice in Million": 20.3, "Runtime in Minutes": 133, "Original Language": "English", "Director": "AlexanderPayne", "release_month": "Nov", "rating": "R", "files": []}
{"Title": "Are You There God? It's Me, Margaret.", "Boxoffice in Million": 20.3, "Runtime in Minutes": 105, "Original Language": "English", "Director": "KellyFremonCraig", "release_month": "Apr", "rating": "PG-13", "files": []}
{"Title": "Past Lives", "Boxoffice in Million": 9.9, "Runtime in Minutes": 106, "Original Language": "English", "Director": "CelineSong", "release_month": "Jun", "rating": "PG-13", "files": []}
{"Title": "Air", "Boxoffice in Million": 52.4, "Runtime in Minutes": 112, "Original Language": "English", "Director": "BenAffleck", "release_month": "Apr", "rating": "R", "files": []}
{"Title": "John Wick: Chapter 4", "Boxoffice in Million": 187.1, "Runtime in Minutes": 169, "Original Language": "English", "Director": "ChadStahelski", "release_month": "Mar", "rating": "R", "files": []}
{"Title": "Barbie", "Boxoffice in Million": 636.2, "Runtime in Minutes": 114, "Original Language": "English", "Director": "GretaGerwig", "release_month": "Jul", "rating": "PG-13", "files": []}
{"Title": "Spider-Man: Across the Spider-Verse", "Boxoffice in Million": 381.2, "Runtime in Minutes": 140, "Original Language": "English", "Director": "JoaquimDosSantos", "release_month": "Jun", "rating": "PG", "files": []}
{"Title": "Killers of the Flower Moon", "Boxoffice in Million": 68.0, "Runtime in Minutes": 206, "Original Language": "English", "Director": "MartinScorsese", "release_month": "Oct", "rating": "R", "files": []}
{"Title": "Mission: Impossible - Dead Reckoning Part One", "Boxoffice in Million": 172.0, "Runtime in Minutes": 163, "Original Language": "English", "Director": "ChristopherMcQuarrie", "release_month": "Jul", "rating": "PG-13", "files": []}
{"Title": "A Thousand and One", "Boxoffice in Million": 3.4, "Runtime in Minutes": 117, "Original Language": "English", "Director": "A.V.Rockwell", "release_month": "Mar", "rating": "R", "files": []}
{"Title": "All of Us Strangers", "Boxoffice in Million": 4.0, "Runtime in Minutes": 105, "Original Language": "English", "Director": "AndrewHaigh", "release_month": "Dec", "rating": "R", "files": []}
{"Title": "Guardians of the Galaxy Vol. 3", "Boxoffice in Million": 359.0, "Runtime in Minutes": 150, "Original Language": "English", "Director": "JamesGunn", "release_month": "May", "rating": "PG-13", "files": []}
{"Title": "Parasite", "Boxoffice in Million": 53.4, "Runtime in Minutes": 132, "Original Language": "Korean", "Director": "BongJoonHo", "release_month": "Nov", "rating": "R", "files": []}
{"Title": "Platoon", "Boxoffice in Million": 138.5, "Runtime in Minutes": 120, "Original Language": "English", "Director": "OliverStone", "release_month": "Dec", "rating": "R", "files": []}
{"Title": "Million Dollar Baby", "Boxoffice in Million": 100.4, "Runtime in Minutes": 132, "Original Language": "English", "Director": "ClintEastwood", "release_month": "Dec", "rating": "PG-13", "files": []}
{"Title": "The Departed", "Boxoffice in Million": 132.4, "Runtime in Minutes": 152, "Original Language": "English", "Director": "MartinScorsese", "release_month": "Oct", "rating": "R", "files": []}
{"Title": "Slumdog Millionaire", "Boxoffice in Million": 141.3, "Runtime in Minutes": 116, "Original Language": "English", "Director": "DannyBoyle", "release_month": "Jan", "rating": "R", "files": []}
{"Title": "Birdman or (The Unexpected Virtue of Ignorance)", "Boxoffice in Million": 42.3, "Runtime in Minutes": 119, "Original Language": "English", "Director": "AlejandroGonzálezIñárritu", "release_month": "Jan", "rating": "R", "files": []}
{"Title": "Out of Africa", "Boxoffice in Million": 83.1, "Runtime in Minutes": 160, "Original Language": "English", "Director": "SydneyPollack", "release_month": "Dec", "rating": "PG", "files": []}
{"Title": "Parasite", "Boxoffice in Million": 53.4, "Runtime in Minutes": 132, "Original Language": "Korean", "Director": "BongJoonHo", "release_month": "Nov", "rating": "R", "files": []}
{"Title": "The Last Emperor", "Boxoffice in Million": 43.0, "Runtime in Minutes": 162, "Original Language": "English", "Director": "BernardoBertolucci", "release_month": "Nov", "rating": "PG-13", "files": []}
{"Title": "Chicago", "Boxoffice in Million": 170.7, "Runtime in Minutes": 113, "Original Language": "English", "Director": "RobMarshall", "release_month": "Jan", "rating": "PG-13", "files": []}
{"Title": "Dances With Wolves", "Boxoffice in Million": 184.0, "Runtime in Minutes": 180, "Original Language": "English", "Director": "KevinCostner", "release_month": "Nov", "rating": "PG-13", "files": []}
{"Title": "American Beauty", "Boxoffice in Million": 130.1, "Runtime in Minutes": 122, "Original Language": "English", "Director": "SamMendes", "release_month": "Oct", "rating": "R", "files": []}
{"Title": "Rain Man", "Boxoffice in Million": 171.2, "Runtime in Minutes": 133, "Original Language": "English", "Director": "BarryLevinson", "release_month": "Dec", "rating": "R", "files": []}
{"Title": "Out of Africa", "Boxoffice in Million": 83.1, "Runtime in Minutes": 160, "Original Language": "English", "Director": "SydneyPollack", "release_month": "Dec", "rating": "PG", "files": []}
{"Title": "A Beautiful Mind", "Boxoffice in Million": 170.7, "Runtime in Minutes": 135, "Original Language": "English", "Director": "RonHoward", "release_month": "Jan", "rating": "PG-13", "files": []}
{"Title": "Crash", "Boxoffice in Million": 54.6, "Runtime in Minutes": 112, "Original Language": "English", "Director": "PaulHaggis", "release_month": "May", "rating": "R", "files": []}
{"Title": "Braveheart", "Boxoffice in Million": 75.5, "Runtime in Minutes": 177, "Original Language": "English", "Director": "MelGibson", "release_month": "May", "rating": "R", "files": []}
{"Title": "Forrest Gump", "Boxoffice in Million": 330.3, "Runtime in Minutes": 142, "Original Language": "English", "Director": "RobertZemeckis", "release_month": "Jul", "rating": "PG-13", "files": []}
{"Title": "Green Book", "Boxoffice in Million": 85.1, "Runtime in Minutes": 130, "Original Language": "English", "Director": "PeterFarrelly", "release_month": "Nov", "rating": "PG-13", "files": []}
{"Title": "Gladiator", "Boxoffice in Million": 187.7, "Runtime in Minutes": 154, "Original Language": "English", "Director": "RidleyScott", "release_month": "May", "rating": "R", "files": []}
{"Title": "Driving Miss Daisy", "Boxoffice in Million": 105.6, "Runtime in Minutes": 99, "Original Language": "English", "Director": "BruceBeresford", "release_month": "Dec", "rating": "PG", "files": []}
{"Title": "The English Patient", "Boxoffice in Million": 78.7, "Runtime in Minutes": 162, "Original Language": "English", "Director": "AnthonyMinghella", "release_month": "Nov", "rating": "R", "files": []}
{"Title": "Platoon", "Boxoffice in Million": 138.5, "Runtime in Minutes": 120, "Original Language": "English", "Director": "OliverStone", "release_month": "Dec", "rating": "R", "files": []}
{"Title": "Million Dollar Baby", "Boxoffice in Million": 100.4, "Runtime in Minutes": 132, "Original Language": "English", "Director": "ClintEastwood", "release_month": "Dec", "rating": "PG-13", "files": []}
{"Title": "The Departed", "Boxoffice in Million": 132.4, "Runtime in Minutes": 152, "Original Language": "English", "Director": "MartinScorsese", "release_month": "Oct", "rating": "R", "files": []}
{"Title": "Slumdog Millionaire", "Boxoffice in Million": 141.3, "Runtime in Minutes": 116, "Original Language": "English", "Director": "DannyBoyle", "release_month": "Jan", "rating": "R", "files": []}
{"Title": "Birdman or (The Unexpected Virtue of Ignorance)", "Boxoffice in Million": 42.3, "Runtime in Minutes": 119, "Original Language": "English", "Director": "AlejandroGonzálezIñárritu", "release_month": "Jan", "rating": "R", "files": []}
{"Title": "Shakespeare in Love", "Boxoffice in Million": 100.2, "Runtime in Minutes": 122, "Original Language": "English", "Director": "JohnMadden", "release_month": "Dec", "rating": "R", "files": []}
{"Title": "The Shape of Water", "Boxoffice in Million": 63.3, "Runtime in Minutes": 123, "Original Language": "English", "Director": "GuillermodelToro", "release_month": "Dec", "rating": "R", "files": []}
{"Title": "Oppenheimer", "Boxoffice in Million": 329.3, "Runtime in Minutes": 180, "Original Language": "English", "Director": "ChristopherNolan", "release_month": "Jul", "rating": "R", "files": []}
