{"Title": "The Wedding Banquet", "Boxoffice in Million": 6.9, "Runtime in Minutes": 107, "Original Language": "Chinese", "Director": "AngLee", "release_month": "Aug", "rating": "R", "audience_score": 87.0, "tomato_score": 97.0, "files": []}
{"Title": "Bride & Prejudice", "Boxoffice in Million": 6.6, "Runtime in Minutes": 110, "Original Language": "English", "Director": "GurinderChadha", "release_month": "Feb", "rating": "PG-13", "audience_score": 70.0, "tomato_score": 64.0, "files": []}
{"Title": "Linsanity", "Boxoffice in Million": 0.25989999999999996, "Runtime in Minutes": 88, "Original Language": "English", "Director": "EvanJacksonLeong", "release_month": "Oct", "rating": "PG", "audience_score": 78.0, "tomato_score": 65.0, "files": []}
{"Title": "Ping Pong Playa", "Boxoffice in Million": 0.0778, "Runtime in Minutes": 96, "Original Language": "English", "Director": "JessicaYu", "release_month": "Sep", "rating": "PG-13", "audience_score": 52.0, "tomato_score": 66.0, "files": []}
{"Title": "A Very Harold & Kumar Christmas", "Boxoffice in Million": 35.0, "Runtime in Minutes": 90, "Original Language": "English", "Director": "ToddStrauss-Schulson", "release_month": "Nov", "rating": "R", "audience_score": 59.0, "tomato_score": 68.0, "files": []}
{"Title": "Blue Bayou", "Boxoffice in Million": 0.6457999999999999, "Runtime in Minutes": 119, "Original Language": "English", "Director": "JustinChon", "release_month": "Sep", "rating": "R", "audience_score": 93.0, "tomato_score": 75.0, "files": []}
{"Title": "Charlotte Sometimes", "Boxoffice in Million": 0.0835, "Runtime in Minutes": 85, "Original Language": "English", "Director": "EricByler", "release_month": "May", "rating": "R", "audience_score": 73.0, "tomato_score": 81.0, "files": []}
{"Title": "Better Luck Tomorrow", "Boxoffice in Million": 3.8, "Runtime in Minutes": 101, "Original Language": "English", "Director": "JustinLin", "release_month": "Apr", "rating": "R", "audience_score": 79.0, "tomato_score": 81.0, "files": []}
{"Title": "Bride & Prejudice", "Boxoffice in Million": 6.6, "Runtime in Minutes": 110, "Original Language": "English", "Director": "GurinderChadha", "release_month": "Feb", "rating": "PG-13", "audience_score": 70.0, "tomato_score": 64.0, "files": []}
{"Title": "Scary Stories to Tell in the Dark", "Boxoffice in Million": 68.7, "Runtime in Minutes": 111, "Original Language": "English", "Director": "AndréØvredal", "release_month": "Aug", "rating": "PG-13", "audience_score": 72.0, "tomato_score": 77.0, "files": []}
{"Title": "1408", "Boxoffice in Million": 72.0, "Runtime in Minutes": 94, "Original Language": "English", "Director": "MikaelHåfström", "release_month": "Jun", "rating": "PG-13", "audience_score": 61.0, "tomato_score": 80.0, "files": []}
{"Title": "Frailty", "Boxoffice in Million": 13.1, "Runtime in Minutes": 99, "Original Language": "English", "Director": "BillPaxton", "release_month": "Apr", "rating": "R", "audience_score": 78.0, "tomato_score": 75.0, "files": []}
{"Title": "Bram Stoker's Dracula", "Boxoffice in Million": 82.0, "Runtime in Minutes": 123, "Original Language": "English", "Director": "FrancisFordCoppola", "release_month": "Nov", "rating": "R", "audience_score": 79.0, "tomato_score": 78.0, "files": []}
{"Title": "Dawn of the Dead", "Boxoffice in Million": 58.9, "Runtime in Minutes": 100, "Original Language": "English", "Director": "ZackSnyder", "release_month": "Mar", "rating": "R", "audience_score": 77.0, "tomato_score": 76.0, "files": []}
{"Title": "The Lost Boys", "Boxoffice in Million": 31.7, "Runtime in Minutes": 97, "Original Language": "English", "Director": "JoelSchumacher", "release_month": "Jul", "rating": "R", "audience_score": 85.0, "tomato_score": 77.0, "files": []}
{"Title": "Species II", "Boxoffice in Million": 19.2, "Runtime in Minutes": 93, "Original Language": "English", "Director": "PeterMedak", "release_month": "Apr", "rating": "R", "audience_score": 18.0, "tomato_score": 9.0, "files": []}
{"Title": "Deuce Bigalow: European Gigolo", "Boxoffice in Million": 22.3, "Runtime in Minutes": 83, "Original Language": "English", "Director": "MikeBigelow", "release_month": "Aug", "rating": "R", "audience_score": 33.0, "tomato_score": 9.0, "files": []}
{"Title": "Little Fockers", "Boxoffice in Million": 148.4, "Runtime in Minutes": 97, "Original Language": "English", "Director": "PaulWeitz", "release_month": "Dec", "rating": "PG-13", "audience_score": 34.0, "tomato_score": 9.0, "files": []}
{"Title": "Halloween: The Curse of Michael Myers", "Boxoffice in Million": 14.7, "Runtime in Minutes": 88, "Original Language": "English", "Director": "JoeChappelle", "release_month": "Sep", "rating": "R", "audience_score": 36.0, "tomato_score": 8.0, "files": []}
{"Title": "Ford v Ferrari", "Boxoffice in Million": 117.6, "Runtime in Minutes": 152, "Original Language": "English", "Director": "JamesMangold", "release_month": "Nov", "rating": "PG-13", "audience_score": 98.0, "tomato_score": 92.0, "files": []}
{"Title": "Creed", "Boxoffice in Million": 109.7, "Runtime in Minutes": 133, "Original Language": "English", "Director": "RyanCoogler", "release_month": "Nov", "rating": "PG-13", "audience_score": 89.0, "tomato_score": 95.0, "files": []}
{"Title": "I, Tonya", "Boxoffice in Million": 30.0, "Runtime in Minutes": 121, "Original Language": "English", "Director": "CraigGillespie", "release_month": "Jan", "rating": "R", "audience_score": 88.0, "tomato_score": 90.0, "files": []}
{"Title": "The Wrestler", "Boxoffice in Million": 26.2, "Runtime in Minutes": 110, "Original Language": "English", "Director": "DarrenAronofsky", "release_month": "Dec", "rating": "R", "audience_score": 88.0, "tomato_score": 98.0, "files": []}
{"Title": "Fighting With My Family", "Boxoffice in Million": 23.0, "Runtime in Minutes": 107, "Original Language": "English", "Director": "StephenMerchant", "release_month": "Feb", "rating": "PG-13", "audience_score": 86.0, "tomato_score": 93.0, "files": []}
{"Title": "Moneyball", "Boxoffice in Million": 75.6, "Runtime in Minutes": 133, "Original Language": "English", "Director": "BennettMiller", "release_month": "Sep", "rating": "PG-13", "audience_score": 86.0, "tomato_score": 94.0, "files": []}
{"Title": "Bull Durham", "Boxoffice in Million": 49.9, "Runtime in Minutes": 108, "Original Language": "English", "Director": "RonShelton", "release_month": "Jun", "rating": "R", "audience_score": 82.0, "tomato_score": 97.0, "files": []}
{"Title": "Raging Bull", "Boxoffice in Million": 0.0873, "Runtime in Minutes": 128, "Original Language": "English", "Director": "MartinScorsese", "release_month": "Jan", "rating": "R", "audience_score": 93.0, "tomato_score": 92.0, "files": []}
{"Title": "Murderball", "Boxoffice in Million": 1.5, "Runtime in Minutes": 85, "Original Language": "English", "Director": "HenryAlexRubin", "release_month": "Jul", "rating": "R", "audience_score": 89.0, "tomato_score": 98.0, "files": []}
{"Title": "Win Win", "Boxoffice in Million": 10.2, "Runtime in Minutes": 106, "Original Language": "English", "Director": "TomMcCarthy", "release_month": "Mar", "rating": "R", "audience_score": 85.0, "tomato_score": 94.0, "files": []}
{"Title": "The King of Kong: A Fistful of Quarters", "Boxoffice in Million": 0.6748999999999999, "Runtime in Minutes": 79, "Original Language": "English", "Director": "SethGordon", "release_month": "Aug", "rating": "PG-13", "audience_score": 93.0, "tomato_score": 97.0, "files": []}
{"Title": "Racing Dreams", "Boxoffice in Million": 0.055600000000000004, "Runtime in Minutes": 97, "Original Language": "English", "Director": "MarshallCurry", "release_month": "May", "rating": "PG", "audience_score": 93.0, "tomato_score": 100.0, "files": []}
{"Title": "Creed II", "Boxoffice in Million": 115.7, "Runtime in Minutes": 130, "Original Language": "English", "Director": "StevenCapleJr.", "release_month": "Nov", "rating": "PG-13", "audience_score": 80.0, "tomato_score": 83.0, "files": []}
{"Title": "Foxcatcher", "Boxoffice in Million": 12.1, "Runtime in Minutes": 134, "Original Language": "English", "Director": "BennettMiller", "release_month": "Nov", "rating": "R", "audience_score": 66.0, "tomato_score": 87.0, "files": []}
{"Title": "The Fighter", "Boxoffice in Million": 93.6, "Runtime in Minutes": 116, "Original Language": "English", "Director": "DavidO.Russell", "release_month": "Dec", "rating": "R", "audience_score": 89.0, "tomato_score": 91.0, "files": []}
{"Title": "Rush", "Boxoffice in Million": 26.9, "Runtime in Minutes": 123, "Original Language": "English", "Director": "RonHoward", "release_month": "Sep", "rating": "R", "audience_score": 88.0, "tomato_score": 88.0, "files": []}
{"Title": "Million Dollar Baby", "Boxoffice in Million": 100.4, "Runtime in Minutes": 132, "Original Language": "English", "Director": "ClintEastwood", "release_month": "Dec", "rating": "PG-13", "audience_score": 90.0, "tomato_score": 90.0, "files": []}
{"Title": "Bigger, Stronger, Faster", "Boxoffice in Million": 0.3078, "Runtime in Minutes": 105, "Original Language": "English", "Director": "ChrisBell", "release_month": "May", "rating": "PG-13", "audience_score": 81.0, "tomato_score": 96.0, "files": []}
{"Title": "The Life and Times of Hank Greenberg", "Boxoffice in Million": 1.7, "Runtime in Minutes": 89, "Original Language": "English", "Director": "AvivaKempner", "release_month": "Jul", "rating": "PG", "audience_score": 81.0, "tomato_score": 97.0, "files": []}
{"Title": "Sugar", "Boxoffice in Million": 1.1, "Runtime in Minutes": 118, "Original Language": "English", "Director": "AnnaBoden", "release_month": "Apr", "rating": "R", "audience_score": 79.0, "tomato_score": 92.0, "files": []}
{"Title": "Touching the Void", "Boxoffice in Million": 4.6, "Runtime in Minutes": 107, "Original Language": "English(UnitedKingdom)", "Director": "KevinMacdonald", "release_month": "Sep", "rating": "R", "audience_score": 92.0, "tomato_score": 94.0, "files": []}
{"Title": "Lagaan: Once Upon a Time in India", "Boxoffice in Million": 0.9058999999999999, "Runtime in Minutes": 223, "Original Language": "Hindi", "Director": "AshutoshGowariker", "release_month": "May", "rating": "PG", "audience_score": 93.0, "tomato_score": 95.0, "files": []}
{"Title": "Offside", "Boxoffice in Million": 0.1799, "Runtime in Minutes": 92, "Original Language": "Persian", "Director": "JafarPanahi", "release_month": "Mar", "rating": "PG", "audience_score": 74.0, "tomato_score": 94.0, "files": []}
{"Title": "The Damned United", "Boxoffice in Million": 0.4496, "Runtime in Minutes": 97, "Original Language": "English", "Director": "TomHooper", "release_month": "Oct", "rating": "R", "audience_score": 85.0, "tomato_score": 92.0, "files": []}
{"Title": "Red Army", "Boxoffice in Million": 0.7287, "Runtime in Minutes": 85, "Original Language": "English", "Director": "GabePolsky", "release_month": "Jan", "rating": "PG", "audience_score": 85.0, "tomato_score": 92.0, "files": []}
{"Title": "Hoosiers", "Boxoffice in Million": 25.8, "Runtime in Minutes": 114, "Original Language": "English", "Director": "DavidAnspaugh", "release_month": "Nov", "rating": "PG", "audience_score": 88.0, "tomato_score": 91.0, "files": []}
{"Title": "A Prayer Before Dawn", "Boxoffice in Million": 0.0145, "Runtime in Minutes": 117, "Original Language": "English", "Director": "Jean-StéphaneSauvaire", "release_month": "Aug", "rating": "R", "audience_score": 75.0, "tomato_score": 92.0, "files": []}
{"Title": "Riding Giants", "Boxoffice in Million": 2.3, "Runtime in Minutes": 102, "Original Language": "English", "Director": "StacyPeralta", "release_month": "Jan", "rating": "PG-13", "audience_score": 94.0, "tomato_score": 93.0, "files": []}
{"Title": "Dogtown and Z-Boys", "Boxoffice in Million": 1.3, "Runtime in Minutes": 89, "Original Language": "English", "Director": "StacyPeralta", "release_month": "Apr", "rating": "PG-13", "audience_score": 88.0, "tomato_score": 92.0, "files": []}
{"Title": "The Color of Money", "Boxoffice in Million": 52.3, "Runtime in Minutes": 119, "Original Language": "English", "Director": "MartinScorsese", "release_month": "Oct", "rating": "R", "audience_score": 73.0, "tomato_score": 88.0, "files": []}
{"Title": "Dream Horse", "Boxoffice in Million": 2.6, "Runtime in Minutes": 113, "Original Language": "English", "Director": "EurosLyn", "release_month": "May", "rating": "PG", "audience_score": 97.0, "tomato_score": 88.0, "files": []}
{"Title": "Field of Dreams", "Boxoffice in Million": 61.8, "Runtime in Minutes": 106, "Original Language": "English", "Director": "PhilAldenRobinson", "release_month": "Apr", "rating": "PG", "audience_score": 86.0, "tomato_score": 88.0, "files": []}
{"Title": "Meru", "Boxoffice in Million": 2.3, "Runtime in Minutes": 90, "Original Language": "English", "Director": "JimmyChin", "release_month": "Aug", "rating": "R", "audience_score": 91.0, "tomato_score": 88.0, "files": []}
{"Title": "Whip It", "Boxoffice in Million": 13.0, "Runtime in Minutes": 111, "Original Language": "English", "Director": "DrewBarrymore", "release_month": "Oct", "rating": "PG-13", "audience_score": 74.0, "tomato_score": 85.0, "files": []}
{"Title": "Eddie the Eagle", "Boxoffice in Million": 15.8, "Runtime in Minutes": 105, "Original Language": "English", "Director": "DexterFletcher", "release_month": "Feb", "rating": "PG-13", "audience_score": 82.0, "tomato_score": 81.0, "files": []}
{"Title": "Eight Men Out", "Boxoffice in Million": 4.3, "Runtime in Minutes": 119, "Original Language": "English", "Director": "JohnSayles", "release_month": "Sep", "rating": "PG", "audience_score": 79.0, "tomato_score": 87.0, "files": []}
{"Title": "Warrior", "Boxoffice in Million": 13.7, "Runtime in Minutes": 139, "Original Language": "English", "Director": "GavinO'Connor", "release_month": "Sep", "rating": "PG-13", "audience_score": 92.0, "tomato_score": 84.0, "files": []}
{"Title": "The Heart of the Game", "Boxoffice in Million": 0.44410000000000005, "Runtime in Minutes": 105, "Original Language": "English", "Director": "WardSerrill", "release_month": "", "rating": "PG-13", "audience_score": 83.0, "tomato_score": 87.0, "files": []}
{"Title": "Bend It Like Beckham", "Boxoffice in Million": 32.5, "Runtime in Minutes": 112, "Original Language": "English", "Director": "GurinderChadha", "release_month": "Mar", "rating": "PG-13", "audience_score": 73.0, "tomato_score": 85.0, "files": []}
{"Title": "Tyson", "Boxoffice in Million": 0.8871, "Runtime in Minutes": 90, "Original Language": "English", "Director": "JamesToback", "release_month": "Apr", "rating": "R", "audience_score": 79.0, "tomato_score": 86.0, "files": []}
{"Title": "Chariots of Fire", "Boxoffice in Million": null, "Runtime in Minutes": 123, "Original Language": "English(UnitedKingdom)", "Director": "HughHudson", "release_month": "Sep", "rating": "PG", "audience_score": 80.0, "tomato_score": 83.0, "files": []}
{"Title": "42", "Boxoffice in Million": 95.1, "Runtime in Minutes": 128, "Original Language": "English", "Director": "BrianHelgeland", "release_month": "Apr", "rating": "PG-13", "audience_score": 85.0, "tomato_score": 81.0, "files": []}
{"Title": "Early Man", "Boxoffice in Million": 8.2, "Runtime in Minutes": 89, "Original Language": "English", "Director": "NickPark", "release_month": "Feb", "rating": "PG", "audience_score": 49.0, "tomato_score": 80.0, "files": []}
{"Title": "Jerry Maguire", "Boxoffice in Million": 153.6, "Runtime in Minutes": 138, "Original Language": "English", "Director": "CameronCrowe", "release_month": "Dec", "rating": "R", "audience_score": 79.0, "tomato_score": 84.0, "files": []}
{"Title": "Big Fan", "Boxoffice in Million": 0.2344, "Runtime in Minutes": 88, "Original Language": "English", "Director": "RobertD.Siegel", "release_month": "Aug", "rating": "R", "audience_score": 62.0, "tomato_score": 85.0, "files": []}
{"Title": "The Hurricane", "Boxoffice in Million": 50.7, "Runtime in Minutes": 146, "Original Language": "English", "Director": "NormanJewison", "release_month": "Jan", "rating": "R", "audience_score": 87.0, "tomato_score": 82.0, "files": []}
{"Title": "Cinderella Man", "Boxoffice in Million": 61.6, "Runtime in Minutes": 144, "Original Language": "English", "Director": "RonHoward", "release_month": "Jun", "rating": "PG-13", "audience_score": 91.0, "tomato_score": 80.0, "files": []}
{"Title": "Love & Basketball", "Boxoffice in Million": 27.4, "Runtime in Minutes": 124, "Original Language": "English", "Director": "GinaPrince-Bythewood", "release_month": "Apr", "rating": "PG-13", "audience_score": 95.0, "tomato_score": 85.0, "files": []}
{"Title": "Friday Night Lights", "Boxoffice in Million": 61.2, "Runtime in Minutes": 117, "Original Language": "English", "Director": "PeterBerg", "release_month": "Oct", "rating": "PG-13", "audience_score": 85.0, "tomato_score": 82.0, "files": []}
{"Title": "The Armstrong Lie", "Boxoffice in Million": 0.3817, "Runtime in Minutes": 122, "Original Language": "English", "Director": "AlexGibney", "release_month": "Nov", "rating": "R", "audience_score": 76.0, "tomato_score": 82.0, "files": []}
{"Title": "The World's Fastest Indian", "Boxoffice in Million": 5.1, "Runtime in Minutes": 127, "Original Language": "English", "Director": "RogerDonaldson", "release_month": "Dec", "rating": "PG-13", "audience_score": 89.0, "tomato_score": 82.0, "files": []}
{"Title": "A League of Their Own", "Boxoffice in Million": 105.1, "Runtime in Minutes": 126, "Original Language": "English", "Director": "PennyMarshall", "release_month": "Jul", "rating": "PG", "audience_score": 84.0, "tomato_score": 81.0, "files": []}
{"Title": "McFarland, USA", "Boxoffice in Million": 44.5, "Runtime in Minutes": 129, "Original Language": "English", "Director": "NikiCaro", "release_month": "Feb", "rating": "PG", "audience_score": 88.0, "tomato_score": 80.0, "files": []}
{"Title": "Goon", "Boxoffice in Million": 4.2, "Runtime in Minutes": 91, "Original Language": "English", "Director": "MichaelDowse", "release_month": "Mar", "rating": "R", "audience_score": 71.0, "tomato_score": 81.0, "files": []}
{"Title": "Major League", "Boxoffice in Million": 49.8, "Runtime in Minutes": 107, "Original Language": "English", "Director": "DavidS.Ward", "release_month": "Apr", "rating": "R", "audience_score": 84.0, "tomato_score": 83.0, "files": []}
{"Title": "Invictus", "Boxoffice in Million": 37.5, "Runtime in Minutes": 134, "Original Language": "English", "Director": "ClintEastwood", "release_month": "Dec", "rating": "PG-13", "audience_score": 75.0, "tomato_score": 76.0, "files": []}
{"Title": "Miracle", "Boxoffice in Million": 64.4, "Runtime in Minutes": 135, "Original Language": "English", "Director": "GavinO'Connor", "release_month": "Feb", "rating": "PG", "audience_score": 90.0, "tomato_score": 81.0, "files": []}
{"Title": "Beyond the Mat", "Boxoffice in Million": 2.0, "Runtime in Minutes": 102, "Original Language": "English", "Director": "BarryW.Blaustein", "release_month": "Mar", "rating": "R", "audience_score": 83.0, "tomato_score": 82.0, "files": []}
{"Title": "The Boxer", "Boxoffice in Million": 5.8, "Runtime in Minutes": 113, "Original Language": "English", "Director": "JimSheridan", "release_month": "Dec", "rating": "R", "audience_score": 74.0, "tomato_score": 81.0, "files": []}
{"Title": "Rocky Balboa", "Boxoffice in Million": 70.3, "Runtime in Minutes": 102, "Original Language": "English", "Director": "SylvesterStallone", "release_month": "Dec", "rating": "PG", "audience_score": 76.0, "tomato_score": 78.0, "files": []}
{"Title": "Seabiscuit", "Boxoffice in Million": 120.1, "Runtime in Minutes": 140, "Original Language": "English", "Director": "GaryRoss", "release_month": "Jul", "rating": "PG-13", "audience_score": 76.0, "tomato_score": 78.0, "files": []}
{"Title": "He Got Game", "Boxoffice in Million": 21.6, "Runtime in Minutes": 134, "Original Language": "English", "Director": "SpikeLee", "release_month": "Apr", "rating": "R", "audience_score": 83.0, "tomato_score": 80.0, "files": []}
{"Title": "Step Into Liquid", "Boxoffice in Million": 3.7, "Runtime in Minutes": 87, "Original Language": "English", "Director": "DanaBrown", "release_month": "Aug", "rating": "PG", "audience_score": 92.0, "tomato_score": 80.0, "files": []}
{"Title": "Rudy", "Boxoffice in Million": 20.7, "Runtime in Minutes": 113, "Original Language": "English", "Director": "DavidAnspaugh", "release_month": "Sep", "rating": "PG", "audience_score": 90.0, "tomato_score": 77.0, "files": []}
{"Title": "White Men Can't Jump", "Boxoffice in Million": 71.6, "Runtime in Minutes": 114, "Original Language": "English", "Director": "RonShelton", "release_month": "Mar", "rating": "R", "audience_score": 69.0, "tomato_score": 75.0, "files": []}
{"Title": "Without Limits", "Boxoffice in Million": 0.7774, "Runtime in Minutes": 117, "Original Language": "English", "Director": "RobertTowne", "release_month": "Sep", "rating": "PG-13", "audience_score": 91.0, "tomato_score": 79.0, "files": []}
{"Title": "The Hammer", "Boxoffice in Million": 0.44260000000000005, "Runtime in Minutes": 93, "Original Language": "English", "Director": "CharlesHerman-Wurmfeld", "release_month": "Mar", "rating": "R", "audience_score": 90.0, "tomato_score": 82.0, "files": []}
{"Title": "Cool Runnings", "Boxoffice in Million": 68.8, "Runtime in Minutes": 97, "Original Language": "English", "Director": "JonTurteltaub", "release_month": "Oct", "rating": "PG", "audience_score": 81.0, "tomato_score": 76.0, "files": []}
{"Title": "Talladega Nights: The Ballad of Ricky Bobby", "Boxoffice in Million": 148.2, "Runtime in Minutes": 110, "Original Language": "English", "Director": "AdamMcKay", "release_month": "Aug", "rating": "PG-13", "audience_score": 73.0, "tomato_score": 71.0, "files": []}
{"Title": "Remember the Titans", "Boxoffice in Million": 115.8, "Runtime in Minutes": 113, "Original Language": "English", "Director": "BoazYakin", "release_month": "Sep", "rating": "PG", "audience_score": 93.0, "tomato_score": 72.0, "files": []}
{"Title": "Invincible", "Boxoffice in Million": 57.8, "Runtime in Minutes": 104, "Original Language": "English", "Director": "EricsonCore", "release_month": "Aug", "rating": "PG", "audience_score": 73.0, "tomato_score": 72.0, "files": []}
{"Title": "Dodgeball: A True Underdog Story", "Boxoffice in Million": 114.3, "Runtime in Minutes": 92, "Original Language": "English", "Director": "RawsonMarshallThurber", "release_month": "Jun", "rating": "PG-13", "audience_score": 76.0, "tomato_score": 71.0, "files": []}
{"Title": "Bethany Hamilton: Unstoppable", "Boxoffice in Million": 0.59, "Runtime in Minutes": 98, "Original Language": "English", "Director": "AaronLieber", "release_month": "Jul", "rating": "PG", "audience_score": 95.0, "tomato_score": 74.0, "files": []}
{"Title": "The Blind Side", "Boxoffice in Million": 256.0, "Runtime in Minutes": 128, "Original Language": "English", "Director": "JohnLeeHancock", "release_month": "Nov", "rating": "PG-13", "audience_score": 85.0, "tomato_score": 66.0, "files": []}
{"Title": "Olympic Dreams", "Boxoffice in Million": 0.0277, "Runtime in Minutes": 83, "Original Language": "English", "Director": "JeremyTeicher", "release_month": "Feb", "rating": "PG-13", "audience_score": 54.0, "tomato_score": 70.0, "files": []}
{"Title": "Fever Pitch", "Boxoffice in Million": 42.1, "Runtime in Minutes": 103, "Original Language": "English", "Director": "RobertFarrelly", "release_month": "Apr", "rating": "PG-13", "audience_score": 60.0, "tomato_score": 66.0, "files": []}
{"Title": "More Than a Game", "Boxoffice in Million": 0.9445, "Runtime in Minutes": 105, "Original Language": "English", "Director": "KristopherBelman", "release_month": "Oct", "rating": "PG", "audience_score": 86.0, "tomato_score": 71.0, "files": []}
{"Title": "Million Dollar Arm", "Boxoffice in Million": 36.4, "Runtime in Minutes": 123, "Original Language": "English", "Director": "CraigGillespie", "release_month": "May", "rating": "PG", "audience_score": 68.0, "tomato_score": 65.0, "files": []}
{"Title": "Coach Carter", "Boxoffice in Million": 67.3, "Runtime in Minutes": 136, "Original Language": "English", "Director": "ThomasCarter", "release_month": "Jan", "rating": "PG-13", "audience_score": 85.0, "tomato_score": 64.0, "files": []}
{"Title": "Race", "Boxoffice in Million": 19.1, "Runtime in Minutes": 134, "Original Language": "English", "Director": "StephenHopkins", "release_month": "Feb", "rating": "PG-13", "audience_score": 77.0, "tomato_score": 63.0, "files": []}
{"Title": "The Sandlot", "Boxoffice in Million": 31.7, "Runtime in Minutes": 101, "Original Language": "English", "Director": "DavidM.Evans", "release_month": "Apr", "rating": "PG", "audience_score": 89.0, "tomato_score": 65.0, "files": []}
{"Title": "Secretariat", "Boxoffice in Million": 59.7, "Runtime in Minutes": 123, "Original Language": "English", "Director": "RandallWallace", "release_month": "Oct", "rating": "PG", "audience_score": 76.0, "tomato_score": 64.0, "files": []}
{"Title": "Dreamer: Inspired by a True Story", "Boxoffice in Million": 32.7, "Runtime in Minutes": 98, "Original Language": "English", "Director": "JohnGatins", "release_month": "Oct", "rating": "PG", "audience_score": 78.0, "tomato_score": 64.0, "files": []}
{"Title": "Bring It On", "Boxoffice in Million": 68.3, "Runtime in Minutes": 98, "Original Language": "English", "Director": "PeytonReed", "release_month": "Aug", "rating": "PG-13", "audience_score": 66.0, "tomato_score": 65.0, "files": []}
{"Title": "The Express", "Boxoffice in Million": 9.6, "Runtime in Minutes": 129, "Original Language": "English", "Director": "GaryFleder", "release_month": "Oct", "rating": "PG", "audience_score": 75.0, "tomato_score": 62.0, "files": []}
{"Title": "The Greatest Game Ever Played", "Boxoffice in Million": 15.3, "Runtime in Minutes": 115, "Original Language": "English", "Director": "BillPaxton", "release_month": "Sep", "rating": "PG", "audience_score": 82.0, "tomato_score": 63.0, "files": []}
{"Title": "Blue Crush", "Boxoffice in Million": 40.1, "Runtime in Minutes": 104, "Original Language": "English", "Director": "JohnStockwell", "release_month": "Aug", "rating": "PG-13", "audience_score": 58.0, "tomato_score": 61.0, "files": []}
{"Title": "A Haunted House 2", "Boxoffice in Million": 17.3, "Runtime in Minutes": 87, "Original Language": "English", "Director": "MikeTiddes", "release_month": "Apr", "rating": "R", "audience_score": 43.0, "tomato_score": 8.0, "files": []}
{"Title": "Rings", "Boxoffice in Million": 27.8, "Runtime in Minutes": 97, "Original Language": "English", "Director": "F.JavierGutiérrez", "release_month": "Feb", "rating": "PG-13", "audience_score": 23.0, "tomato_score": 8.0, "files": []}
{"Title": "Grown Ups 2", "Boxoffice in Million": 133.7, "Runtime in Minutes": 100, "Original Language": "English", "Director": "DennisDugan", "release_month": "Jul", "rating": "PG-13", "audience_score": 53.0, "tomato_score": 8.0, "files": []}
{"Title": "Problem Child 2", "Boxoffice in Million": 25.1, "Runtime in Minutes": 91, "Original Language": "English", "Director": "BrianLevant", "release_month": "Jul", "rating": "PG-13", "audience_score": 42.0, "tomato_score": 7.0, "files": []}
{"Title": "National Lampoon's Van Wilder: The Rise of Taj", "Boxoffice in Million": 4.3, "Runtime in Minutes": 98, "Original Language": "English", "Director": "MortNathan", "release_month": "Dec", "rating": "R", "audience_score": 38.0, "tomato_score": 7.0, "files": []}
{"Title": "I Still Know What You Did Last Summer", "Boxoffice in Million": 40.0, "Runtime in Minutes": 101, "Original Language": "English", "Director": "DannyCannon", "release_month": "Nov", "rating": "R", "audience_score": 29.0, "tomato_score": 7.0, "files": []}
{"Title": "Paul Blart: Mall Cop 2", "Boxoffice in Million": 71.0, "Runtime in Minutes": 94, "Original Language": "English", "Director": "AndyFickman", "release_month": "Apr", "rating": "PG", "audience_score": 34.0, "tomato_score": 6.0, "files": []}
{"Title": "Cheaper by the Dozen 2", "Boxoffice in Million": 82.6, "Runtime in Minutes": 94, "Original Language": "English", "Director": "AdamShankman", "release_month": "Dec", "rating": "PG", "audience_score": 57.0, "tomato_score": 6.0, "files": []}
{"Title": "Son of the Mask", "Boxoffice in Million": 17.0, "Runtime in Minutes": 95, "Original Language": "English", "Director": "LawrenceGuterman", "release_month": "Feb", "rating": "PG", "audience_score": 16.0, "tomato_score": 6.0, "files": []}
{"Title": "Basic Instinct 2", "Boxoffice in Million": 5.9, "Runtime in Minutes": 115, "Original Language": "English", "Director": "MichaelCaton-Jones", "release_month": "Mar", "rating": "R", "audience_score": 26.0, "tomato_score": 6.0, "files": []}
{"Title": "Major League II", "Boxoffice in Million": 29.4, "Runtime in Minutes": 104, "Original Language": "English", "Director": "DavidS.Ward", "release_month": "Mar", "rating": "PG", "audience_score": 45.0, "tomato_score": 5.0, "files": []}
{"Title": "Universal Soldier: The Return", "Boxoffice in Million": 10.4, "Runtime in Minutes": 82, "Original Language": "English", "Director": "MicRodgers", "release_month": "Aug", "rating": "R", "audience_score": 24.0, "tomato_score": 5.0, "files": []}
{"Title": "Big Mommas: Like Father, Like Son", "Boxoffice in Million": 37.9, "Runtime in Minutes": 108, "Original Language": "English", "Director": "JohnWhitesell", "release_month": "Feb", "rating": "PG-13", "audience_score": 58.0, "tomato_score": 5.0, "files": []}
{"Title": "Big Momma's House 2", "Boxoffice in Million": 70.2, "Runtime in Minutes": 99, "Original Language": "English", "Director": "JohnWhitesell", "release_month": "Jan", "rating": "PG-13", "audience_score": 58.0, "tomato_score": 5.0, "files": []}
{"Title": "Atlas Shrugged: Part 2", "Boxoffice in Million": 3.3, "Runtime in Minutes": 112, "Original Language": "English", "Director": "JohnPutch", "release_month": "Oct", "rating": "PG-13", "audience_score": 60.0, "tomato_score": 4.0, "files": []}
{"Title": "Tyler Perry's Boo 2! A Madea Halloween", "Boxoffice in Million": 47.3, "Runtime in Minutes": 101, "Original Language": "English", "Director": "TylerPerry", "release_month": "Oct", "rating": "PG-13", "audience_score": 41.0, "tomato_score": 4.0, "files": []}
{"Title": "Scary Movie V", "Boxoffice in Million": 32.0, "Runtime in Minutes": 85, "Original Language": "English", "Director": "MalcolmD.Lee", "release_month": "Apr", "rating": "PG-13", "audience_score": 38.0, "tomato_score": 4.0, "files": []}
{"Title": "Mortal Kombat Annihilation", "Boxoffice in Million": 35.9, "Runtime in Minutes": 94, "Original Language": "English", "Director": "JohnR.Leonetti", "release_month": "Nov", "rating": "PG-13", "audience_score": 24.0, "tomato_score": 4.0, "files": []}
{"Title": "Daddy Day Camp", "Boxoffice in Million": 13.2, "Runtime in Minutes": 89, "Original Language": "English", "Director": "FredSavage", "release_month": "Aug", "rating": "PG", "audience_score": 37.0, "tomato_score": 1.0, "files": []}
{"Title": "The Whole Ten Yards", "Boxoffice in Million": 16.3, "Runtime in Minutes": 99, "Original Language": "English", "Director": "HowardDeutch", "release_month": "Apr", "rating": "PG-13", "audience_score": 40.0, "tomato_score": 4.0, "files": []}
{"Title": "The Crow: Wicked Prayer", "Boxoffice in Million": null, "Runtime in Minutes": 99, "Original Language": "English", "Director": "LanceMungia", "release_month": "May", "rating": "R", "audience_score": 35.0, "tomato_score": 0.0, "files": []}
{"Title": "Atlas Shrugged: Who Is John Galt?", "Boxoffice in Million": 0.8302, "Runtime in Minutes": 99, "Original Language": "English", "Director": "JamesManera", "release_month": "Sep", "rating": "PG-13", "audience_score": 41.0, "tomato_score": 0.0, "files": []}
{"Title": "Jaws the Revenge", "Boxoffice in Million": 18.8, "Runtime in Minutes": 89, "Original Language": "English", "Director": "JosephSargent", "release_month": "Jul", "rating": "PG-13", "audience_score": 15.0, "tomato_score": 0.0, "files": []}
{"Title": "SuperBabies: Baby Geniuses 2", "Boxoffice in Million": 9.1, "Runtime in Minutes": 88, "Original Language": "English", "Director": "BobClark", "release_month": "Aug", "rating": "PG", "audience_score": 25.0, "tomato_score": 0.0, "files": []}
{"Title": "Come to Daddy", "Boxoffice in Million": 0.061399999999999996, "Runtime in Minutes": 93, "Original Language": "English", "Director": "AntTimpson", "release_month": "Feb", "rating": "R", "audience_score": 75.0, "tomato_score": 88.0, "files": []}
{"Title": "Overlord", "Boxoffice in Million": 21.7, "Runtime in Minutes": 110, "Original Language": "English", "Director": "JuliusAvery", "release_month": "Nov", "rating": "R", "audience_score": 67.0, "tomato_score": 82.0, "files": []}
{"Title": "Halloween", "Boxoffice in Million": 159.5, "Runtime in Minutes": 106, "Original Language": "English", "Director": "DavidGordonGreen", "release_month": "Oct", "rating": "R", "audience_score": 72.0, "tomato_score": 79.0, "files": []}
{"Title": "Bubba Ho-Tep", "Boxoffice in Million": 0.8919, "Runtime in Minutes": 92, "Original Language": "English", "Director": "DonCoscarelli", "release_month": "Jun", "rating": "R", "audience_score": 79.0, "tomato_score": 79.0, "files": []}
{"Title": "Werewolves Within", "Boxoffice in Million": 0.5756, "Runtime in Minutes": 97, "Original Language": "English", "Director": "JoshRuben", "release_month": "Jun", "rating": "R", "audience_score": 80.0, "tomato_score": 86.0, "files": []}
{"Title": "Smile", "Boxoffice in Million": 105.9, "Runtime in Minutes": 116, "Original Language": "English", "Director": "ParkerFinn", "release_month": "Sep", "rating": "R", "audience_score": 77.0, "tomato_score": 79.0, "files": []}
{"Title": "The House of the Devil", "Boxoffice in Million": 0.1007, "Runtime in Minutes": 93, "Original Language": "English", "Director": "TiWest", "release_month": "Oct", "rating": "R", "audience_score": 63.0, "tomato_score": 85.0, "files": []}
{"Title": "Split", "Boxoffice in Million": 138.1, "Runtime in Minutes": 117, "Original Language": "English", "Director": "M.NightShyamalan", "release_month": "Jan", "rating": "PG-13", "audience_score": 79.0, "tomato_score": 78.0, "files": []}
{"Title": "Thirst", "Boxoffice in Million": 0.2964, "Runtime in Minutes": 133, "Original Language": "English", "Director": "ParkChan-wook", "release_month": "Jul", "rating": "R", "audience_score": 74.0, "tomato_score": 81.0, "files": []}
{"Title": "Near Dark", "Boxoffice in Million": 2.5, "Runtime in Minutes": 95, "Original Language": "English", "Director": "KathrynBigelow", "release_month": "Oct", "rating": "R", "audience_score": 74.0, "tomato_score": 83.0, "files": []}
{"Title": "Shadow of the Vampire", "Boxoffice in Million": 8.3, "Runtime in Minutes": 93, "Original Language": "English", "Director": "E.EliasMerhige", "release_month": "Jan", "rating": "R", "audience_score": 74.0, "tomato_score": 82.0, "files": []}
{"Title": "Warm Bodies", "Boxoffice in Million": 66.4, "Runtime in Minutes": 98, "Original Language": "English", "Director": "JonathanLevine", "release_month": "Feb", "rating": "PG-13", "audience_score": 73.0, "tomato_score": 81.0, "files": []}
{"Title": "Midsommar", "Boxoffice in Million": 27.4, "Runtime in Minutes": 145, "Original Language": "English", "Director": "AriAster", "release_month": "Aug", "rating": "R", "audience_score": 63.0, "tomato_score": 83.0, "files": []}
{"Title": "Goodnight Mommy", "Boxoffice in Million": 1.2, "Runtime in Minutes": 100, "Original Language": "German", "Director": "VeronikaFranz", "release_month": "Sep", "rating": "R", "audience_score": 66.0, "tomato_score": 85.0, "files": []}
{"Title": "Predator", "Boxoffice in Million": 54.4, "Runtime in Minutes": 107, "Original Language": "English", "Director": "JohnMcTiernan", "release_month": "Jun", "rating": "R", "audience_score": 87.0, "tomato_score": 80.0, "files": []}
{"Title": "Saw X", "Boxoffice in Million": 53.4, "Runtime in Minutes": 118, "Original Language": "English", "Director": "KevinGreutert", "release_month": "Sep", "rating": "R", "audience_score": 89.0, "tomato_score": 80.0, "files": []}
{"Title": "Scream", "Boxoffice in Million": 103.7, "Runtime in Minutes": 111, "Original Language": "English", "Director": "WesCraven", "release_month": "Dec", "rating": "R", "audience_score": 80.0, "tomato_score": 81.0, "files": []}
{"Title": "Better Watch Out", "Boxoffice in Million": 0.020300000000000002, "Runtime in Minutes": 89, "Original Language": "English", "Director": "ChrisPeckover", "release_month": "Oct", "rating": "R", "audience_score": 64.0, "tomato_score": 88.0, "files": []}
{"Title": "The Conjuring 2", "Boxoffice in Million": 102.5, "Runtime in Minutes": 133, "Original Language": "English", "Director": "JamesWan", "release_month": "Jun", "rating": "R", "audience_score": 81.0, "tomato_score": 80.0, "files": []}
{"Title": "Scream VI", "Boxoffice in Million": 108.1, "Runtime in Minutes": 123, "Original Language": "English", "Director": "MattBettinelli-Olpin", "release_month": "Mar", "rating": "R", "audience_score": 91.0, "tomato_score": 76.0, "files": []}
{"Title": "Doctor Sleep", "Boxoffice in Million": 31.6, "Runtime in Minutes": 151, "Original Language": "English", "Director": "MikeFlanagan", "release_month": "Nov", "rating": "R", "audience_score": 89.0, "tomato_score": 78.0, "files": []}
{"Title": "Crawl", "Boxoffice in Million": 39.0, "Runtime in Minutes": 87, "Original Language": "English", "Director": "AlexandreAja", "release_month": "Jul", "rating": "R", "audience_score": 75.0, "tomato_score": 84.0, "files": []}
{"Title": "Slither", "Boxoffice in Million": 7.8, "Runtime in Minutes": 96, "Original Language": "English", "Director": "JamesGunn", "release_month": "Mar", "rating": "R", "audience_score": 63.0, "tomato_score": 87.0, "files": []}
{"Title": "Nope", "Boxoffice in Million": 123.2, "Runtime in Minutes": 135, "Original Language": "English", "Director": "JordanPeele", "release_month": "Jul", "rating": "R", "audience_score": 69.0, "tomato_score": 83.0, "files": []}
{"Title": "Dead Ringers", "Boxoffice in Million": 8.3, "Runtime in Minutes": 115, "Original Language": "English", "Director": "DavidCronenberg", "release_month": "Sep", "rating": "R", "audience_score": 82.0, "tomato_score": 85.0, "files": []}
{"Title": "Candyman", "Boxoffice in Million": 61.2, "Runtime in Minutes": 91, "Original Language": "English", "Director": "NiaDaCosta", "release_month": "Aug", "rating": "R", "audience_score": 72.0, "tomato_score": 84.0, "files": []}
{"Title": "Evil Dead Rise", "Boxoffice in Million": 67.2, "Runtime in Minutes": 96, "Original Language": "English", "Director": "LeeCronin", "release_month": "Apr", "rating": "R", "audience_score": 76.0, "tomato_score": 84.0, "files": []}
{"Title": "The Exorcist", "Boxoffice in Million": 441.4, "Runtime in Minutes": 122, "Original Language": "English", "Director": "WilliamFriedkin", "release_month": "Dec", "rating": "R", "audience_score": 87.0, "tomato_score": 78.0, "files": []}
{"Title": "Tremors", "Boxoffice in Million": 15.5, "Runtime in Minutes": 96, "Original Language": "English", "Director": "RonUnderwood", "release_month": "Jan", "rating": "PG-13", "audience_score": 75.0, "tomato_score": 88.0, "files": []}
{"Title": "Freaky", "Boxoffice in Million": 9.0, "Runtime in Minutes": 101, "Original Language": "English", "Director": "ChristopherLandon", "release_month": "Nov", "rating": "R", "audience_score": 80.0, "tomato_score": 83.0, "files": []}
{"Title": "The Night House", "Boxoffice in Million": 7.1, "Runtime in Minutes": 110, "Original Language": "English", "Director": "DavidBruckner", "release_month": "Aug", "rating": "R", "audience_score": 69.0, "tomato_score": 88.0, "files": []}
{"Title": "Gremlins", "Boxoffice in Million": null, "Runtime in Minutes": 106, "Original Language": "English", "Director": "JoeDante", "release_month": "Jun", "rating": "PG", "audience_score": 78.0, "tomato_score": 86.0, "files": []}
{"Title": "Only Lovers Left Alive", "Boxoffice in Million": 1.9, "Runtime in Minutes": 122, "Original Language": "English", "Director": "JimJarmusch", "release_month": "Apr", "rating": "R", "audience_score": 75.0, "tomato_score": 86.0, "files": []}
{"Title": "Rare Exports: A Christmas Tale", "Boxoffice in Million": 0.2632, "Runtime in Minutes": 84, "Original Language": "Finnish", "Director": "JalmariHelander", "release_month": "Dec", "rating": "R", "audience_score": 70.0, "tomato_score": 89.0, "files": []}
{"Title": "The Others", "Boxoffice in Million": 0.0135, "Runtime in Minutes": 101, "Original Language": "English", "Director": "AlejandroAmenábar", "release_month": "Aug", "rating": "PG-13", "audience_score": 77.0, "tomato_score": 84.0, "files": []}
{"Title": "Annihilation", "Boxoffice in Million": 32.7, "Runtime in Minutes": 115, "Original Language": "English", "Director": "AlexGarland", "release_month": "Feb", "rating": "R", "audience_score": 67.0, "tomato_score": 88.0, "files": []}
{"Title": "Tucker & Dale vs Evil", "Boxoffice in Million": 0.2236, "Runtime in Minutes": 89, "Original Language": "English", "Director": "EliCraig", "release_month": "Sep", "rating": "R", "audience_score": 85.0, "tomato_score": 85.0, "files": []}
{"Title": "Poltergeist", "Boxoffice in Million": 121.8, "Runtime in Minutes": 114, "Original Language": "English", "Director": "TobeHooper", "release_month": "Jun", "rating": "PG", "audience_score": 79.0, "tomato_score": 88.0, "files": []}
{"Title": "The Descent", "Boxoffice in Million": 26.0, "Runtime in Minutes": 99, "Original Language": "English", "Director": "NeilMarshall", "release_month": "Aug", "rating": "R", "audience_score": 76.0, "tomato_score": 87.0, "files": []}
{"Title": "Grindhouse", "Boxoffice in Million": 25.0, "Runtime in Minutes": 191, "Original Language": "English", "Director": "QuentinTarantino", "release_month": "Apr", "rating": "R", "audience_score": 87.0, "tomato_score": 84.0, "files": []}
{"Title": "The Blackening", "Boxoffice in Million": 17.7, "Runtime in Minutes": 97, "Original Language": "English", "Director": "TimStory", "release_month": "Jun", "rating": "R", "audience_score": 85.0, "tomato_score": 87.0, "files": []}
{"Title": "The Conjuring", "Boxoffice in Million": 137.4, "Runtime in Minutes": 111, "Original Language": "English", "Director": "JamesWan", "release_month": "Jul", "rating": "R", "audience_score": 83.0, "tomato_score": 86.0, "files": []}
{"Title": "Don't Breathe", "Boxoffice in Million": 89.2, "Runtime in Minutes": 88, "Original Language": "English", "Director": "FedeAlvarez", "release_month": "Aug", "rating": "R", "audience_score": 79.0, "tomato_score": 88.0, "files": []}
{"Title": "Let Me In", "Boxoffice in Million": 12.1, "Runtime in Minutes": 115, "Original Language": "English", "Director": "MattReeves", "release_month": "Oct", "rating": "R", "audience_score": 76.0, "tomato_score": 88.0, "files": []}
{"Title": "You Won't Be Alone", "Boxoffice in Million": 0.2349, "Runtime in Minutes": 109, "Original Language": "Macedonian", "Director": "GoranStolevski", "release_month": "Apr", "rating": "R", "audience_score": 71.0, "tomato_score": 93.0, "files": []}
{"Title": "Dead Alive", "Boxoffice in Million": 0.0705, "Runtime in Minutes": 101, "Original Language": "English", "Director": "PeterJackson", "release_month": "Feb", "rating": "R", "audience_score": 86.0, "tomato_score": 89.0, "files": []}
{"Title": "Drag Me to Hell", "Boxoffice in Million": 42.1, "Runtime in Minutes": 99, "Original Language": "English", "Director": "SamRaimi", "release_month": "May", "rating": "PG-13", "audience_score": 62.0, "tomato_score": 92.0, "files": []}
{"Title": "Hereditary", "Boxoffice in Million": 44.1, "Runtime in Minutes": 127, "Original Language": "English", "Director": "AriAster", "release_month": "Jun", "rating": "R", "audience_score": 70.0, "tomato_score": 90.0, "files": []}
{"Title": "Beast", "Boxoffice in Million": 0.7934, "Runtime in Minutes": 107, "Original Language": "English(UnitedKingdom)", "Director": "MichaelPearce", "release_month": "May", "rating": "R", "audience_score": 73.0, "tomato_score": 92.0, "files": []}
{"Title": "Green Room", "Boxoffice in Million": 3.2, "Runtime in Minutes": 94, "Original Language": "English", "Director": "JeremySaulnier", "release_month": "Apr", "rating": "R", "audience_score": 75.0, "tomato_score": 90.0, "files": []}
{"Title": "It", "Boxoffice in Million": 327.5, "Runtime in Minutes": 135, "Original Language": "English", "Director": "AndyMuschietti", "release_month": "Sep", "rating": "R", "audience_score": 84.0, "tomato_score": 85.0, "files": []}
{"Title": "The Lighthouse", "Boxoffice in Million": 10.9, "Runtime in Minutes": 110, "Original Language": "English", "Director": "RobertEggers", "release_month": "Oct", "rating": "R", "audience_score": 72.0, "tomato_score": 90.0, "files": []}
{"Title": "Ready or Not", "Boxoffice in Million": 28.7, "Runtime in Minutes": 95, "Original Language": "English", "Director": "MattBettinelli-Olpin", "release_month": "Aug", "rating": "R", "audience_score": 78.0, "tomato_score": 89.0, "files": []}
{"Title": "Evil Dead 2", "Boxoffice in Million": 2.6, "Runtime in Minutes": 85, "Original Language": "English", "Director": "SamRaimi", "release_month": "Mar", "rating": "R", "audience_score": 89.0, "tomato_score": 88.0, "files": []}
{"Title": "Upgrade", "Boxoffice in Million": 11.8, "Runtime in Minutes": 95, "Original Language": "English", "Director": "LeighWhannell", "release_month": "Jun", "rating": "R", "audience_score": 88.0, "tomato_score": 88.0, "files": []}
{"Title": "Us", "Boxoffice in Million": 175.0, "Runtime in Minutes": 116, "Original Language": "English", "Director": "JordanPeele", "release_month": "Mar", "rating": "R", "audience_score": 60.0, "tomato_score": 93.0, "files": []}
{"Title": "Barbarian", "Boxoffice in Million": 40.8, "Runtime in Minutes": 102, "Original Language": "English", "Director": "ZachCregger", "release_month": "Sep", "rating": "R", "audience_score": 71.0, "tomato_score": 93.0, "files": []}
{"Title": "The Orphanage", "Boxoffice in Million": 7.2, "Runtime in Minutes": 105, "Original Language": "Spanish(Spain)", "Director": "J.A.Bayona", "release_month": "Jan", "rating": "R", "audience_score": 86.0, "tomato_score": 87.0, "files": []}
{"Title": "Attack the Block", "Boxoffice in Million": 1.0, "Runtime in Minutes": 88, "Original Language": "English", "Director": "JoeCornish", "release_month": "Jul", "rating": "R", "audience_score": 75.0, "tomato_score": 91.0, "files": []}
{"Title": "28 Days Later", "Boxoffice in Million": 45.1, "Runtime in Minutes": 112, "Original Language": "English", "Director": "DannyBoyle", "release_month": "Jun", "rating": "R", "audience_score": 85.0, "tomato_score": 87.0, "files": []}
{"Title": "10 Cloverfield Lane", "Boxoffice in Million": 72.1, "Runtime in Minutes": 103, "Original Language": "English", "Director": "DanTrachtenberg", "release_month": "Mar", "rating": "PG-13", "audience_score": 79.0, "tomato_score": 90.0, "files": []}
{"Title": "Raw", "Boxoffice in Million": 0.5084, "Runtime in Minutes": 98, "Original Language": "French(France)", "Director": "JuliaDucournau", "release_month": "Mar", "rating": "R", "audience_score": 76.0, "tomato_score": 93.0, "files": []}
{"Title": "It Follows", "Boxoffice in Million": 14.7, "Runtime in Minutes": 101, "Original Language": "English", "Director": "DavidRobertMitchell", "release_month": "Mar", "rating": "R", "audience_score": 66.0, "tomato_score": 95.0, "files": []}
{"Title": "The Cabin in the Woods", "Boxoffice in Million": 42.0, "Runtime in Minutes": 95, "Original Language": "English", "Director": "DrewGoddard", "release_month": "Apr", "rating": "R", "audience_score": 74.0, "tomato_score": 92.0, "files": []}
{"Title": "Misery", "Boxoffice in Million": 54.7, "Runtime in Minutes": 107, "Original Language": "English", "Director": "RobReiner", "release_month": "Nov", "rating": "R", "audience_score": 90.0, "tomato_score": 91.0, "files": []}
{"Title": "X", "Boxoffice in Million": 11.6, "Runtime in Minutes": 105, "Original Language": "English", "Director": "TiWest", "release_month": "Mar", "rating": "R", "audience_score": 75.0, "tomato_score": 94.0, "files": []}
{"Title": "The Birds", "Boxoffice in Million": null, "Runtime in Minutes": 119, "Original Language": "English", "Director": "AlfredHitchcock", "release_month": "Mar", "rating": "PG-13", "audience_score": 83.0, "tomato_score": 94.0, "files": []}
{"Title": "Zombieland", "Boxoffice in Million": 75.6, "Runtime in Minutes": 87, "Original Language": "English", "Director": "RubenFleischer", "release_month": "Oct", "rating": "R", "audience_score": 86.0, "tomato_score": 89.0, "files": []}
{"Title": "Pearl", "Boxoffice in Million": 8.2, "Runtime in Minutes": 102, "Original Language": "English", "Director": "TiWest", "release_month": "Sep", "rating": "R", "audience_score": 83.0, "tomato_score": 93.0, "files": []}
{"Title": "The Fly", "Boxoffice in Million": 34.9, "Runtime in Minutes": 95, "Original Language": "English", "Director": "DavidCronenberg", "release_month": "Aug", "rating": "R", "audience_score": 83.0, "tomato_score": 93.0, "files": []}
{"Title": "M3GAN", "Boxoffice in Million": 95.0, "Runtime in Minutes": 102, "Original Language": "English", "Director": "GerardJohnstone", "release_month": "Jan", "rating": "PG-13", "audience_score": 78.0, "tomato_score": 93.0, "files": []}
{"Title": "Border", "Boxoffice in Million": 0.7719, "Runtime in Minutes": 108, "Original Language": "Swedish", "Director": "AliAbbasi", "release_month": "Oct", "rating": "R", "audience_score": 76.0, "tomato_score": 97.0, "files": []}
{"Title": "Under the Shadow", "Boxoffice in Million": 0.0258, "Runtime in Minutes": 84, "Original Language": "Persian", "Director": "BabakAnvari", "release_month": "Oct", "rating": "PG-13", "audience_score": 71.0, "tomato_score": 99.0, "files": []}
{"Title": "A Nightmare on Elm Street", "Boxoffice in Million": 57.3, "Runtime in Minutes": 91, "Original Language": "English", "Director": "WesCraven", "release_month": "Nov", "rating": "R", "audience_score": 84.0, "tomato_score": 95.0, "files": []}
{"Title": "Talk to Me", "Boxoffice in Million": 47.6, "Runtime in Minutes": 95, "Original Language": "English", "Director": "DannyPhilippou", "release_month": "Jul", "rating": "R", "audience_score": 82.0, "tomato_score": 95.0, "files": []}
{"Title": "Night of the Living Dead", "Boxoffice in Million": 0.0687, "Runtime in Minutes": 96, "Original Language": "", "Director": "KarlHardman", "release_month": "", "rating": "", "audience_score": 87.0, "tomato_score": 95.0, "files": []}
{"Title": "A Quiet Place Part II", "Boxoffice in Million": 160.2, "Runtime in Minutes": 97, "Original Language": "English", "Director": "JohnKrasinski", "release_month": "May", "rating": "PG-13", "audience_score": 92.0, "tomato_score": 91.0, "files": []}
{"Title": "The Invisible Man", "Boxoffice in Million": 64.3, "Runtime in Minutes": 124, "Original Language": "English", "Director": "LeighWhannell", "release_month": "Feb", "rating": "R", "audience_score": 88.0, "tomato_score": 92.0, "files": []}
{"Title": "What We Do in the Shadows", "Boxoffice in Million": 3.3, "Runtime in Minutes": 86, "Original Language": "English", "Director": "JemaineClement", "release_month": "Feb", "rating": "R", "audience_score": 87.0, "tomato_score": 96.0, "files": []}
